name: "Caramelo Papelaria"
bio: "A papelaria mais doce que existe"
meta:
  lang: "pt_br"
  description: "A papelaria mais doce que existe"
  title: "Caramelo Papelaria"
  author: "Patterson"
  siteUrl: "https://caramelo-papelaria.github.io/"
links:
  - name: "Shopee"
    url: "https://shopee.com.br/pattriziaol"
  - name: "Instagram"
    url: "https://www.instagram.com/caramelo.papelaria/"
  - name: "Threads"
    url: "https://www.threads.com/@caramelo.papelaria"
  # - name: ""
  #   url: ""
theme: "custom"
